### ISSUE TITLE
Adding 'userId' when I add a new recipient.

### ISSUE THREAD

**Issue by devinrbopp** [WDI-SEA/project-2-issues#10]
I have a table `recipients` that is linked to the user table, so that when you are logged in, any recipients you add will be linked to your id, but I can't figure out how to have the logged in user's id get added to the `recipients` table. I tried the following in my controller:

```js
// POST create new recipient form
router.post('/', (req, res) => {
    console.log(req.body)
    db.recipient.create({
        firstName: req.body.firstName,
        lastName: req.body.lastName,
        relationship: req.body.relationship,
        userId: currentUser.id
    })
    .then((recipient) => {
        res.redirect('/recipients')
    })
    .catch((error) => (
        console.error()
    ))
})
```

This gives me the following error:
```
ReferenceError: currentUser is not defined
    at /Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/controllers/recipients.js:29:17
    at Layer.handle [as handle_request] (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/layer.js:95:5)
    at /Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/devinbopp/SEI_pumpkin_smashers/projects/holiday-shopping-planning/node_modules/express/lib/router/index.js:47:12)
```

This makes sense--the route doesn't know what `currentUser` is. But I see in profile.ejs the following:
```ejs
<h2><%= currentUser.name %>'s Profile</h2>
```

Any ideas what the best way to reference the user number is?

Thanks!

**Comment by devinrbopp** [comment]
Actually, I fixed it! I added a hidden form field to the add recipient form:
```ejs
<input type="integer" name="userId" value="<%= currentUser.id %>" hidden>
```

And I added the middleware and isLoggedIn argument to the controller:
```js
const isLoggedIn = require('../middleware/isLoggedIn')
// ETC
// POST create new recipient form
router.post('/', isLoggedIn, (req, res) => {
    console.log(req.body)
    db.recipient.create({
        firstName: req.body.firstName,
        lastName: req.body.lastName,
        relationship: req.body.relationship,
        userId: req.body.userId
    })
    .then((recipient) => {
        res.redirect('/recipients')
    })
    .catch((error) => (
        console.error()
    ))
```
Please let me know if there is a preferred way to handle this! Next step will be have the recipients index display ONLY recipients with the currently logged in user's userId.

Thanks!

**Comment by tkolsrud** [comment]
Nice one!
