### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by shuzel99** [WDI-SEA/project-2-issues#51]
When I press my 'Add to' button in the browser there's an error in my database 
`original: error: column "modelId" does not exist
      at Parser.parseErrorMessage (C:\Users\shuze\sei_pumpkin_smashers\projects\seiPenApp\node_modules\pg-protocol\dist\parser.js:278:15)  
      at Parser.handlePacket (C:\Users\shuze\sei_pumpkin_smashers\projects\seiPenApp\node_modules\pg-protocol\dist\parser.js:126:29)       
      at Parser.parse (C:\Users\shuze\sei_pumpkin_smashers\projects\seiPenApp\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\Users\shuze\sei_pumpkin_smashers\projects\seiPenApp\node_modules\pg-protocol\dist\index.js:10:42)`
Not sure where/how to add modelId

**Comment by tkolsrud** [comment]
have you checked psql to make sure the table is in your database?

**Comment by shuzel99** [comment]
yes, I have all my tables in there

**Comment by DoireannJane** [comment]
I forgot to ask Shuzel were there changes to your model and did you migrate the changes?

**Comment by shuzel99** [comment]
I migrated it when I first saw the error to make sure but it said there weren't any changes

**Comment by DoireannJane** [comment]
Hm ok, let's take a look at your models, requirements and your table in your db first.
